### ISSUE TITLE
Running superDev mode?

### ISSUE THREAD

**Issue by danielvaughan** [feedm3/spring-boot-gwt#3]
Is it possible to run superDev mode with this project?

**Comment by feedm3** [comment]
Of course, just start it in IntelliJ with the given GWT configuration (or create a new one on your own).

I have to say that I dont know how to start it with eclipse or gradle because I do all my GWT development with IntelliJ.

**Comment by jhonsmall** [comment]
its possible with eclipse: in Debug Configurations , Arguments
-war /home/jhon/xxx/devSpringGWT_P/yyyBoot/SPRING_GWTP/yyyCoop/build -startupUrl index.html -logLevel INFO -port 8888 -remoteUI "${gwt_remote_ui_server_port}:${unique_id}" -codeServerPort 9997 aa.bbb.ccc.SpringBootGwt

In Java Build Path is Source: src/main/resources/static Output folder to build

**Comment by danielvaughan** [comment]
Thanks, I did what I thought was the tricky bit, getting GWT-RPC to work under Spring Boot but the  superDev was still and issue. I will give it a go.

**Comment by danielvaughan** [comment]
Yes, happily got superDev mode working now.
