### ISSUE TITLE
Run IDEA configuration

### ISSUE THREAD

**Issue by alabotski** [feedm3/spring-boot-gwt#6]
Can you help me
How I can run this project from IDEA?

_java -jar example.jar_ work well
But when I run it on IDEA run configuration, work only server side.

[some info](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000047324-Run-Spring-Boot-Gradle-GWT?page=1#community_comment_360000041430)

**Comment by feedm3** [comment]
You need to create a run configuration in IntelliJ for both the backend (Spring Boot run configuration) and the frontend (GWT run configuration). Both can be run separately during development, they only get merged into one jar (example.jar) when you build a release.

**Comment by alabotski** [comment]
But I delete webapp directory and move all html into resource static

**Comment by feedm3** [comment]
Yeah, you have to change that in your GWT configuration as stated in the readme:

> Note that you have to set the path to the static html file in your project strutures "Web" module to the static/resource folder. Otherwise GWT will not find the index.html.

**Comment by alabotski** [comment]
Run config. Don't see any index.html =((( 

When I try add _resource/static_

![selection_009](https://user-images.githubusercontent.com/439337/35859468-35f47006-0b51-11e8-936f-1beccbc5d2e8.png)

**Comment by feedm3** [comment]
Open "Project structure" in IDEA and check if the GWT module is correct. There you also need to specify the path.

**Comment by alabotski** [comment]
Now It's dont correct
I delete 

plugin war  and assembling into war

**Comment by alabotski** [comment]
Can you attach some screenshot from idea? =(I can not start =(

**Comment by alabotski** [comment]
I run gwt local

**Comment by feedm3** [comment]
Sorry for the late reply, I've added a detailed description on how to configure everything in IntelliJ:

https://github.com/feedm3/spring-boot-gwt/blob/master/docs/IDEA_SETTINGS.md
