### ISSUE TITLE
How to run gwt on Spring Boot server with SSL enabled?

### ISSUE THREAD

**Issue by pedy711** [feedm3/spring-boot-gwt#8]
Hi everyone, can someone please help me? I have a Spring Boot server with SSL enabled on it. I want to use SmartGwt as GUI side of my application. But I get this: 

    Couldn't load App from Super Dev Mode server at http://192.168.0.241:9876. Please make sure this 
    server is ready. Do you want to try again?

and when I enable "load unsafe script" on Chrome I still get the followings on the console: 

    Mixed Content: The page at 'https://192.168.0.241:8090/App.html' was loaded over HTTPS, but 
    requested an insecure script 'http://192.168.0.241:9876/recompile-requester/App'. This content should 
    also be served over HTTPS.

    App.nocache.js:54 GET http://192.168.0.241:9876/recompile-requester/App

I heard that this is possible through a reverse proxy server, but I have no idea where to start from. Any help would be much appreciated.

**Comment by feedm3** [comment]
Closed due to inactivity.
