### ISSUE TITLE
README instructions are contradictory, confusing and bootRun does not work

### ISSUE THREAD

**Issue by deduper** [feedm3/spring-boot-gwt#9]
### The Bug
The web application does not work if you do `gradlew bootRun`. 

The problem is when I do `gradlew bootRun` then load `localhost:8080` in the browser, nothing is rendered in the browser!  Only an empty page is displayed. 

### The Confusion

The README says: „*To run this project you have to start Spring Boot and GWT **separate***“. However, the single instruction that follows that statement (`gradlew bootRun`) does not explain how to start the two „*separate*“. That's a single instruction for how to start Spring Boot. Where is the „*separate*“ instruction explaining how to start GWT?

### The Contradiction

> ...*the finished jar file is in build/libs/spring-boot-gwt-1.0.0.jar and can simply be started with*
> 
>     java -jar build/libs/spring-boot-gwt-1.0.0.jar
> 
> 

You can't run both the `gradlew bootRun` ***and*** the  `java -jar build/libs/spring-boot-gwt-1.0.0.jar` commands „*separately*“. Because the server would already be running by whichever command you execute first.

Thankfully, executing that single  `java -jar build/libs/spring-boot-gwt-1.0.0.jar` command ***only***, and launching `localhost:8080` in the browser, the web app page is rendered and displayed as expected. But that single command is all that is required. What other second, „*separate*“ start command does your first instruction refer to?

### My Environment
OS: Windows
Browser: IE 11
Gradle: 5.2.1
Java: OpenJDK 8

**Comment by feedm3** [comment]
Thanks for the feedback :) This repository is quite old and I'm not maintaining it anymore, but maybe I can help you:

**Run** ("The Confusion"): This chapter explains how you run the project during development. This means, that you compile and run the GWT code with IntelliJ and the server with gradle. Both parts run independently, therefore separat.

**Build** ("The Contradiction"): This chapter explains how you build this project for production. It has nothing todo with the `gradle bootRun` command, stated in the chapter above, as this command is only used during development. Building this project for production with the mentioned gradle command will result in a JAR file, that contains the Spring Boot and GWT code. You can run it with the given `java` command.
